% Flight conditions and atmospheric parameters derived from AVL for the 
% University of Colorado's RAAVEN Unmanned Aircraft
%
%   File created by: Maggie Wussow
%   Data taken from files generated by Maggie Wussow, Robert Sasse and Ceu
%   Falk-Gomez
%       - Derivatives come from AVL analysis
%       - Inertias from Solidworks model
% Last Updated: 9/18/24
%
% AVL called with rho = 1.14; % air density at Boulder [kg/m^3]
%    u0 = 18; 
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% All dimensional parameters in SI units
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [aircraft_parameters] = raaven()

    aircraft_parameters.g = 9.81; % Gravitational acceleration [m/s^2]
    
    
    %Aircraft geometry parameters
    aircraft_parameters.S = 0.8000; %[m^2] % from Xflr5 noNose dimensions
    aircraft_parameters.b = 2.228; %[m] % from Xflr5 noNose dimensions
    aircraft_parameters.c = aircraft_parameters.S/aircraft_parameters.b; %[m] 
    aircraft_parameters.AR = aircraft_parameters.b*aircraft_parameters.b/aircraft_parameters.S;
    
    % Aircraft mass parameters
    aircraft_parameters.m = 6.4; %[kg] % measured by hand 
    aircraft_parameters.W = aircraft_parameters.m*aircraft_parameters.g; %[N]
    
    % Inertias from Solidworks (checked against masses)
    aircraft_parameters.Ix = 0.52; %[kg m^2]
    aircraft_parameters.Iy = 0.54; %[kg m^2]
    aircraft_parameters.Iz = 1.06; %[kg m^2]
    aircraft_parameters.Ixz = 0.0946; %[kg m^2] 
    
    aircraft_parameters.inertia_matrix = [aircraft_parameters.Ix 0 -aircraft_parameters.Ixz; 0 aircraft_parameters.Iy 0; -aircraft_parameters.Ixz 0 aircraft_parameters.Iz];
    
    
    % Drag terms
    aircraft_parameters.e = 0.6162; %[-]
    aircraft_parameters.K = 1/(pi*aircraft_parameters.AR*aircraft_parameters.e); % drag polar coefficient
    aircraft_parameters.CDmin = 0.0148;
    aircraft_parameters.CLmin = 0.477;
      
    % Engine parameters from trial and error
    aircraft_parameters.Sprop = 0.0804; %[m^2]
    aircraft_parameters.Cprop = 1.0;
    aircraft_parameters.kmotor = 32.279;
    
    % Zero angle of attack aerodynamic forces and moments
    aircraft_parameters.CL0 = 0.1492;
    aircraft_parameters.Cm0 = 0.1374;
    
    % Assumed zero
    aircraft_parameters.CY0 = 0;
    aircraft_parameters.Cl0 = 0;
    aircraft_parameters.Cn0 = 0;
    
    % Longtidunal nondimensional stability derivatives from AVL
    aircraft_parameters.CLalpha = 4.232848; 
    aircraft_parameters.Cmalpha = -1.49;
    aircraft_parameters.CLq = 5.468810; 
    aircraft_parameters.Cmq = -2.739887;
    
    
    % Neglected parameters, check units below if incorporated later
    aircraft_parameters.CLalphadot = 0; 
    aircraft_parameters.Cmalphadot = 0; 
    
    
    % Lateral-directional nondimensional stability derivatives from AVL
    aircraft_parameters.CYbeta = -0.221204; 
    aircraft_parameters.Clbeta = 0.000507; 
    aircraft_parameters.Cnbeta = 0.064303; 
    aircraft_parameters.CYp =  0.048123; 
    aircraft_parameters.Clp = -0.373116; 
    aircraft_parameters.Cnp = -0.026358; 
    aircraft_parameters.Clr = 0.092486; 
    aircraft_parameters.Cnr = -0.042330; 
    aircraft_parameters.CYr = 0.144141;  
    
    %Control surface deflection parameters (From AVL)
    
      % Elevator
      aircraft_parameters.Cmde =  -0.2973;  
      aircraft_parameters.CLde =   0.003750; 
      
      % Aileron
      aircraft_parameters.CYda =   0.000274;
      aircraft_parameters.Clda =  -0.01023;
      aircraft_parameters.Cnda =  -0.000094;
     
    %   % Rudder DOES NOT EXIST
      aircraft_parameters.CYdr =  0;
      aircraft_parameters.Cldr =  0;
      aircraft_parameters.Cndr =  0;
    
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % Additional terms needed for linear models
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    inertia_terms = utils.InertiaTerms(aircraft_parameters);
    
    aircraft_parameters.Cp0 = inertia_terms(3)*aircraft_parameters.Cl0 + inertia_terms(4)*aircraft_parameters.Cn0;
    aircraft_parameters.Cpbeta = inertia_terms(3)*aircraft_parameters.Clbeta + inertia_terms(4)*aircraft_parameters.Cnbeta;
    aircraft_parameters.Cpp = inertia_terms(3)*aircraft_parameters.Clp + inertia_terms(4)*aircraft_parameters.Cnp;
    aircraft_parameters.Cpr = inertia_terms(3)*aircraft_parameters.Clr + inertia_terms(4)*aircraft_parameters.Cnr;
    aircraft_parameters.Cpda = inertia_terms(3)*aircraft_parameters.Clda + inertia_terms(4)*aircraft_parameters.Cnda;
    aircraft_parameters.Cpdr = inertia_terms(3)*aircraft_parameters.Cldr + inertia_terms(4)*aircraft_parameters.Cndr;
    
    aircraft_parameters.Cr0 = inertia_terms(4)*aircraft_parameters.Cl0 + inertia_terms(8)*aircraft_parameters.Cn0;
    aircraft_parameters.Crbeta = inertia_terms(4)*aircraft_parameters.Clbeta + inertia_terms(8)*aircraft_parameters.Cnbeta;
    aircraft_parameters.Crp = inertia_terms(4)*aircraft_parameters.Clp + inertia_terms(8)*aircraft_parameters.Cnp;
    aircraft_parameters.Crr = inertia_terms(4)*aircraft_parameters.Clr + inertia_terms(8)*aircraft_parameters.Cnr;
    aircraft_parameters.Crda = inertia_terms(4)*aircraft_parameters.Clda + inertia_terms(8)*aircraft_parameters.Cnda;
    aircraft_parameters.Crdr = inertia_terms(4)*aircraft_parameters.Cldr + inertia_terms(8)*aircraft_parameters.Cndr;

end

  
  
  
  
  
  
